<?php
return array(
    'basePath' => dirname(__FILE__) . DIRECTORY_SEPARATOR . '..',
    'name' => 'Sales Libraries Cron Daemon',
    'preload' => array('log'),
    'import' => array(
        'application.commands.*',
		'application.components.*',
		'application.components.widgets.*',
		'application.components.core.*',
		'application.models.*',
		'application.models.common.*',
		'application.models.rate.*',
		'application.models.auth.models.*',
		'application.models.auth.records.*',
		'application.models.menu.models.*',
		'application.models.menu.records.*',
		'application.models.favorites.models.*',
		'application.models.favorites.records.*',
		'application.models.qpages.models.*',
		'application.models.qpages.records.*',
		'application.models.quizzes.models.*',
		'application.models.quizzes.records.*',
		'application.models.shortcuts.models.*',
		'application.models.shortcuts.records.*',
		'application.models.statistic.models.*',
		'application.models.statistic.records.*',
		'application.models.ticker.models.*',
		'application.models.ticker.records.*',
		'application.models.wallbin.models.*',
		'application.models.wallbin.records.*',
    ),
    'components' => array(
        'db' => array(
            'connectionString' => 'mysql:host=localhost;dbname=sales_library',
            'emulatePrepare' => true,
            'username' => 'root',
            'password' => 'root',
            'charset' => 'utf8',
            'autoConnect' => true,
            'tablePrefix' => 'tbl_',
            'schemaCachingDuration' => 3600,
        ),
        'log' => array(
            'class' => 'CLogRouter',
            'routes' => array(
                array(
                    'class' => 'CFileLogRoute',
                    'levels' => 'error, warning',
                ),
            ),
        ),
        'cacheDB' => array(
            'class' => 'system.caching.CDbCache',
            'connectionID' => 'db',
            'autoCreateCacheTable' => true,
            'cacheTableName' => 'tbl_cache',
        ),
        'email' => array(
            'class' => 'application.extensions.email.Email',
            'delivery' => 'php',
        ),
    ),
    'params' => require(dirname(__FILE__) . '/params.php'),
);
