//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.269.
// 
#pragma warning disable 1591

namespace FileManager.ContentManagmentService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ContentControllerBinding", Namespace="urn:ContentControllerwsdl")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(AutoWidget))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Column))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(LibraryLink))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(LibraryFolder))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(LibraryPage))]
    public partial class ContentControllerService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getSessionKeyOperationCompleted;
        
        private System.Threading.SendOrPostCallback setLibraryOperationCompleted;
        
        private System.Threading.SendOrPostCallback setContentOperationCompleted;
        
        private System.Threading.SendOrPostCallback buildCacheOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ContentControllerService() {
            this.Url = global::FileManager.Properties.Settings.Default.FileManager_ContentManagmentService_ContentControllerService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getSessionKeyCompletedEventHandler getSessionKeyCompleted;
        
        /// <remarks/>
        public event setLibraryCompletedEventHandler setLibraryCompleted;
        
        /// <remarks/>
        public event setContentCompletedEventHandler setContentCompleted;
        
        /// <remarks/>
        public event buildCacheCompletedEventHandler buildCacheCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ContentControllerwsdl#getSessionKey", RequestNamespace="urn:ContentControllerwsdl", ResponseNamespace="urn:ContentControllerwsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string getSessionKey(string login, string password) {
            object[] results = this.Invoke("getSessionKey", new object[] {
                        login,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getSessionKeyAsync(string login, string password) {
            this.getSessionKeyAsync(login, password, null);
        }
        
        /// <remarks/>
        public void getSessionKeyAsync(string login, string password, object userState) {
            if ((this.getSessionKeyOperationCompleted == null)) {
                this.getSessionKeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSessionKeyOperationCompleted);
            }
            this.InvokeAsync("getSessionKey", new object[] {
                        login,
                        password}, this.getSessionKeyOperationCompleted, userState);
        }
        
        private void OngetSessionKeyOperationCompleted(object arg) {
            if ((this.getSessionKeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSessionKeyCompleted(this, new getSessionKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ContentControllerwsdl#setLibrary", RequestNamespace="urn:ContentControllerwsdl", ResponseNamespace="urn:ContentControllerwsdl")]
        public void setLibrary(string sessionKey, Library library) {
            this.Invoke("setLibrary", new object[] {
                        sessionKey,
                        library});
        }
        
        /// <remarks/>
        public void setLibraryAsync(string sessionKey, Library library) {
            this.setLibraryAsync(sessionKey, library, null);
        }
        
        /// <remarks/>
        public void setLibraryAsync(string sessionKey, Library library, object userState) {
            if ((this.setLibraryOperationCompleted == null)) {
                this.setLibraryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetLibraryOperationCompleted);
            }
            this.InvokeAsync("setLibrary", new object[] {
                        sessionKey,
                        library}, this.setLibraryOperationCompleted, userState);
        }
        
        private void OnsetLibraryOperationCompleted(object arg) {
            if ((this.setLibraryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setLibraryCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ContentControllerwsdl#setContent", RequestNamespace="urn:ContentControllerwsdl", ResponseNamespace="urn:ContentControllerwsdl")]
        public void setContent(string sessionKey, string linkId, string content) {
            this.Invoke("setContent", new object[] {
                        sessionKey,
                        linkId,
                        content});
        }
        
        /// <remarks/>
        public void setContentAsync(string sessionKey, string linkId, string content) {
            this.setContentAsync(sessionKey, linkId, content, null);
        }
        
        /// <remarks/>
        public void setContentAsync(string sessionKey, string linkId, string content, object userState) {
            if ((this.setContentOperationCompleted == null)) {
                this.setContentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetContentOperationCompleted);
            }
            this.InvokeAsync("setContent", new object[] {
                        sessionKey,
                        linkId,
                        content}, this.setContentOperationCompleted, userState);
        }
        
        private void OnsetContentOperationCompleted(object arg) {
            if ((this.setContentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setContentCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ContentControllerwsdl#buildCache", RequestNamespace="urn:ContentControllerwsdl", ResponseNamespace="urn:ContentControllerwsdl")]
        public void buildCache(string sessionKey, string libraryId) {
            this.Invoke("buildCache", new object[] {
                        sessionKey,
                        libraryId});
        }
        
        /// <remarks/>
        public void buildCacheAsync(string sessionKey, string libraryId) {
            this.buildCacheAsync(sessionKey, libraryId, null);
        }
        
        /// <remarks/>
        public void buildCacheAsync(string sessionKey, string libraryId, object userState) {
            if ((this.buildCacheOperationCompleted == null)) {
                this.buildCacheOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuildCacheOperationCompleted);
            }
            this.InvokeAsync("buildCache", new object[] {
                        sessionKey,
                        libraryId}, this.buildCacheOperationCompleted, userState);
        }
        
        private void OnbuildCacheOperationCompleted(object arg) {
            if ((this.buildCacheCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buildCacheCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ContentControllerwsdl")]
    public partial class Library {
        
        private string idField;
        
        private string nameField;
        
        private LibraryPage[] pagesField;
        
        private AutoWidget[] autoWidgetsField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public LibraryPage[] pages {
            get {
                return this.pagesField;
            }
            set {
                this.pagesField = value;
            }
        }
        
        /// <remarks/>
        public AutoWidget[] autoWidgets {
            get {
                return this.autoWidgetsField;
            }
            set {
                this.autoWidgetsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ContentControllerwsdl")]
    public partial class LibraryPage {
        
        private string idField;
        
        private string libraryIdField;
        
        private string nameField;
        
        private int orderField;
        
        private LibraryFolder[] foldersField;
        
        private bool enableColumnsField;
        
        private Column[] columnsField;
        
        private string dateModifyField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string libraryId {
            get {
                return this.libraryIdField;
            }
            set {
                this.libraryIdField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
        
        /// <remarks/>
        public LibraryFolder[] folders {
            get {
                return this.foldersField;
            }
            set {
                this.foldersField = value;
            }
        }
        
        /// <remarks/>
        public bool enableColumns {
            get {
                return this.enableColumnsField;
            }
            set {
                this.enableColumnsField = value;
            }
        }
        
        /// <remarks/>
        public Column[] columns {
            get {
                return this.columnsField;
            }
            set {
                this.columnsField = value;
            }
        }
        
        /// <remarks/>
        public string dateModify {
            get {
                return this.dateModifyField;
            }
            set {
                this.dateModifyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ContentControllerwsdl")]
    public partial class LibraryFolder {
        
        private string idField;
        
        private string pageIdField;
        
        private string libraryIdField;
        
        private string nameField;
        
        private int rowOrderField;
        
        private int columnOrderField;
        
        private string borderColorField;
        
        private string windowBackColorField;
        
        private string windowForeColorField;
        
        private string headerBackColorField;
        
        private string headerForeColorField;
        
        private Font windowFontField;
        
        private Font headerFontField;
        
        private string headerAlignmentField;
        
        private bool enableWidgetField;
        
        private string widgetField;
        
        private Banner bannerField;
        
        private LibraryLink[] filesField;
        
        private string dateAddField;
        
        private string dateModifyField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string pageId {
            get {
                return this.pageIdField;
            }
            set {
                this.pageIdField = value;
            }
        }
        
        /// <remarks/>
        public string libraryId {
            get {
                return this.libraryIdField;
            }
            set {
                this.libraryIdField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int rowOrder {
            get {
                return this.rowOrderField;
            }
            set {
                this.rowOrderField = value;
            }
        }
        
        /// <remarks/>
        public int columnOrder {
            get {
                return this.columnOrderField;
            }
            set {
                this.columnOrderField = value;
            }
        }
        
        /// <remarks/>
        public string borderColor {
            get {
                return this.borderColorField;
            }
            set {
                this.borderColorField = value;
            }
        }
        
        /// <remarks/>
        public string windowBackColor {
            get {
                return this.windowBackColorField;
            }
            set {
                this.windowBackColorField = value;
            }
        }
        
        /// <remarks/>
        public string windowForeColor {
            get {
                return this.windowForeColorField;
            }
            set {
                this.windowForeColorField = value;
            }
        }
        
        /// <remarks/>
        public string headerBackColor {
            get {
                return this.headerBackColorField;
            }
            set {
                this.headerBackColorField = value;
            }
        }
        
        /// <remarks/>
        public string headerForeColor {
            get {
                return this.headerForeColorField;
            }
            set {
                this.headerForeColorField = value;
            }
        }
        
        /// <remarks/>
        public Font windowFont {
            get {
                return this.windowFontField;
            }
            set {
                this.windowFontField = value;
            }
        }
        
        /// <remarks/>
        public Font headerFont {
            get {
                return this.headerFontField;
            }
            set {
                this.headerFontField = value;
            }
        }
        
        /// <remarks/>
        public string headerAlignment {
            get {
                return this.headerAlignmentField;
            }
            set {
                this.headerAlignmentField = value;
            }
        }
        
        /// <remarks/>
        public bool enableWidget {
            get {
                return this.enableWidgetField;
            }
            set {
                this.enableWidgetField = value;
            }
        }
        
        /// <remarks/>
        public string widget {
            get {
                return this.widgetField;
            }
            set {
                this.widgetField = value;
            }
        }
        
        /// <remarks/>
        public Banner banner {
            get {
                return this.bannerField;
            }
            set {
                this.bannerField = value;
            }
        }
        
        /// <remarks/>
        public LibraryLink[] files {
            get {
                return this.filesField;
            }
            set {
                this.filesField = value;
            }
        }
        
        /// <remarks/>
        public string dateAdd {
            get {
                return this.dateAddField;
            }
            set {
                this.dateAddField = value;
            }
        }
        
        /// <remarks/>
        public string dateModify {
            get {
                return this.dateModifyField;
            }
            set {
                this.dateModifyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ContentControllerwsdl")]
    public partial class Font {
        
        private string nameField;
        
        private int sizeField;
        
        private bool isBoldField;
        
        private bool isItalicField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
        
        /// <remarks/>
        public bool isBold {
            get {
                return this.isBoldField;
            }
            set {
                this.isBoldField = value;
            }
        }
        
        /// <remarks/>
        public bool isItalic {
            get {
                return this.isItalicField;
            }
            set {
                this.isItalicField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ContentControllerwsdl")]
    public partial class AutoWidget {
        
        private string libraryIdField;
        
        private string extensionField;
        
        private string widgetField;
        
        /// <remarks/>
        public string libraryId {
            get {
                return this.libraryIdField;
            }
            set {
                this.libraryIdField = value;
            }
        }
        
        /// <remarks/>
        public string extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        public string widget {
            get {
                return this.widgetField;
            }
            set {
                this.widgetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ContentControllerwsdl")]
    public partial class Column {
        
        private string pageIdField;
        
        private string libraryIdField;
        
        private string nameField;
        
        private int orderField;
        
        private string backColorField;
        
        private string foreColorField;
        
        private Font fontField;
        
        private bool showTextField;
        
        private string alignmentField;
        
        private bool enableWidgetField;
        
        private string widgetField;
        
        private Banner bannerField;
        
        private string dateModifyField;
        
        /// <remarks/>
        public string pageId {
            get {
                return this.pageIdField;
            }
            set {
                this.pageIdField = value;
            }
        }
        
        /// <remarks/>
        public string libraryId {
            get {
                return this.libraryIdField;
            }
            set {
                this.libraryIdField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
        
        /// <remarks/>
        public string backColor {
            get {
                return this.backColorField;
            }
            set {
                this.backColorField = value;
            }
        }
        
        /// <remarks/>
        public string foreColor {
            get {
                return this.foreColorField;
            }
            set {
                this.foreColorField = value;
            }
        }
        
        /// <remarks/>
        public Font font {
            get {
                return this.fontField;
            }
            set {
                this.fontField = value;
            }
        }
        
        /// <remarks/>
        public bool showText {
            get {
                return this.showTextField;
            }
            set {
                this.showTextField = value;
            }
        }
        
        /// <remarks/>
        public string alignment {
            get {
                return this.alignmentField;
            }
            set {
                this.alignmentField = value;
            }
        }
        
        /// <remarks/>
        public bool enableWidget {
            get {
                return this.enableWidgetField;
            }
            set {
                this.enableWidgetField = value;
            }
        }
        
        /// <remarks/>
        public string widget {
            get {
                return this.widgetField;
            }
            set {
                this.widgetField = value;
            }
        }
        
        /// <remarks/>
        public Banner banner {
            get {
                return this.bannerField;
            }
            set {
                this.bannerField = value;
            }
        }
        
        /// <remarks/>
        public string dateModify {
            get {
                return this.dateModifyField;
            }
            set {
                this.dateModifyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ContentControllerwsdl")]
    public partial class Banner {
        
        private string idField;
        
        private string libraryIdField;
        
        private bool isEnabledField;
        
        private string imageField;
        
        private bool showTextField;
        
        private string imageAlignmentField;
        
        private string textField;
        
        private Font fontField;
        
        private string foreColorField;
        
        private string dateModifyField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string libraryId {
            get {
                return this.libraryIdField;
            }
            set {
                this.libraryIdField = value;
            }
        }
        
        /// <remarks/>
        public bool isEnabled {
            get {
                return this.isEnabledField;
            }
            set {
                this.isEnabledField = value;
            }
        }
        
        /// <remarks/>
        public string image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
            }
        }
        
        /// <remarks/>
        public bool showText {
            get {
                return this.showTextField;
            }
            set {
                this.showTextField = value;
            }
        }
        
        /// <remarks/>
        public string imageAlignment {
            get {
                return this.imageAlignmentField;
            }
            set {
                this.imageAlignmentField = value;
            }
        }
        
        /// <remarks/>
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        public Font font {
            get {
                return this.fontField;
            }
            set {
                this.fontField = value;
            }
        }
        
        /// <remarks/>
        public string foreColor {
            get {
                return this.foreColorField;
            }
            set {
                this.foreColorField = value;
            }
        }
        
        /// <remarks/>
        public string dateModify {
            get {
                return this.dateModifyField;
            }
            set {
                this.dateModifyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ContentControllerwsdl")]
    public partial class UniversalPreviewContainer {
        
        private string linkIdField;
        
        private string libraryIdField;
        
        private string[] pngLinksField;
        
        private string[] jpegLinksField;
        
        private string[] pdfLinksField;
        
        private string[] mp4LinksField;
        
        private string[] ogvLinksField;
        
        private string[] oldOfficeFormatLinksField;
        
        private string[] newOfficeFormatLinksField;
        
        private string[] thumbsLinksField;
        
        private string[] txtLinksField;
        
        private int thumbsWidthField;
        
        private int thumbsHeightField;
        
        /// <remarks/>
        public string linkId {
            get {
                return this.linkIdField;
            }
            set {
                this.linkIdField = value;
            }
        }
        
        /// <remarks/>
        public string libraryId {
            get {
                return this.libraryIdField;
            }
            set {
                this.libraryIdField = value;
            }
        }
        
        /// <remarks/>
        public string[] pngLinks {
            get {
                return this.pngLinksField;
            }
            set {
                this.pngLinksField = value;
            }
        }
        
        /// <remarks/>
        public string[] jpegLinks {
            get {
                return this.jpegLinksField;
            }
            set {
                this.jpegLinksField = value;
            }
        }
        
        /// <remarks/>
        public string[] pdfLinks {
            get {
                return this.pdfLinksField;
            }
            set {
                this.pdfLinksField = value;
            }
        }
        
        /// <remarks/>
        public string[] mp4Links {
            get {
                return this.mp4LinksField;
            }
            set {
                this.mp4LinksField = value;
            }
        }
        
        /// <remarks/>
        public string[] ogvLinks {
            get {
                return this.ogvLinksField;
            }
            set {
                this.ogvLinksField = value;
            }
        }
        
        /// <remarks/>
        public string[] oldOfficeFormatLinks {
            get {
                return this.oldOfficeFormatLinksField;
            }
            set {
                this.oldOfficeFormatLinksField = value;
            }
        }
        
        /// <remarks/>
        public string[] newOfficeFormatLinks {
            get {
                return this.newOfficeFormatLinksField;
            }
            set {
                this.newOfficeFormatLinksField = value;
            }
        }
        
        /// <remarks/>
        public string[] thumbsLinks {
            get {
                return this.thumbsLinksField;
            }
            set {
                this.thumbsLinksField = value;
            }
        }
        
        /// <remarks/>
        public string[] txtLinks {
            get {
                return this.txtLinksField;
            }
            set {
                this.txtLinksField = value;
            }
        }
        
        /// <remarks/>
        public int thumbsWidth {
            get {
                return this.thumbsWidthField;
            }
            set {
                this.thumbsWidthField = value;
            }
        }
        
        /// <remarks/>
        public int thumbsHeight {
            get {
                return this.thumbsHeightField;
            }
            set {
                this.thumbsHeightField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ContentControllerwsdl")]
    public partial class LineBreak {
        
        private string idField;
        
        private string libraryIdField;
        
        private Font fontField;
        
        private string foreColorField;
        
        private string noteField;
        
        private string dateModifyField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string libraryId {
            get {
                return this.libraryIdField;
            }
            set {
                this.libraryIdField = value;
            }
        }
        
        /// <remarks/>
        public Font font {
            get {
                return this.fontField;
            }
            set {
                this.fontField = value;
            }
        }
        
        /// <remarks/>
        public string foreColor {
            get {
                return this.foreColorField;
            }
            set {
                this.foreColorField = value;
            }
        }
        
        /// <remarks/>
        public string note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
            }
        }
        
        /// <remarks/>
        public string dateModify {
            get {
                return this.dateModifyField;
            }
            set {
                this.dateModifyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ContentControllerwsdl")]
    public partial class LibraryLink {
        
        private string idField;
        
        private string folderIdField;
        
        private string libraryIdField;
        
        private string nameField;
        
        private string fileRelativePathField;
        
        private string fileNameField;
        
        private string fileExtensionField;
        
        private string fileDateField;
        
        private string noteField;
        
        private bool isBoldField;
        
        private int orderField;
        
        private int typeField;
        
        private LineBreak lineBreakPropertiesField;
        
        private bool enableWidgetField;
        
        private string widgetField;
        
        private Banner bannerField;
        
        private UniversalPreviewContainer universalPreviewField;
        
        private string tagsField;
        
        private string dateAddField;
        
        private string dateModifyField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string folderId {
            get {
                return this.folderIdField;
            }
            set {
                this.folderIdField = value;
            }
        }
        
        /// <remarks/>
        public string libraryId {
            get {
                return this.libraryIdField;
            }
            set {
                this.libraryIdField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string fileRelativePath {
            get {
                return this.fileRelativePathField;
            }
            set {
                this.fileRelativePathField = value;
            }
        }
        
        /// <remarks/>
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        public string fileExtension {
            get {
                return this.fileExtensionField;
            }
            set {
                this.fileExtensionField = value;
            }
        }
        
        /// <remarks/>
        public string fileDate {
            get {
                return this.fileDateField;
            }
            set {
                this.fileDateField = value;
            }
        }
        
        /// <remarks/>
        public string note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
            }
        }
        
        /// <remarks/>
        public bool isBold {
            get {
                return this.isBoldField;
            }
            set {
                this.isBoldField = value;
            }
        }
        
        /// <remarks/>
        public int order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
        
        /// <remarks/>
        public int type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public LineBreak lineBreakProperties {
            get {
                return this.lineBreakPropertiesField;
            }
            set {
                this.lineBreakPropertiesField = value;
            }
        }
        
        /// <remarks/>
        public bool enableWidget {
            get {
                return this.enableWidgetField;
            }
            set {
                this.enableWidgetField = value;
            }
        }
        
        /// <remarks/>
        public string widget {
            get {
                return this.widgetField;
            }
            set {
                this.widgetField = value;
            }
        }
        
        /// <remarks/>
        public Banner banner {
            get {
                return this.bannerField;
            }
            set {
                this.bannerField = value;
            }
        }
        
        /// <remarks/>
        public UniversalPreviewContainer universalPreview {
            get {
                return this.universalPreviewField;
            }
            set {
                this.universalPreviewField = value;
            }
        }
        
        /// <remarks/>
        public string tags {
            get {
                return this.tagsField;
            }
            set {
                this.tagsField = value;
            }
        }
        
        /// <remarks/>
        public string dateAdd {
            get {
                return this.dateAddField;
            }
            set {
                this.dateAddField = value;
            }
        }
        
        /// <remarks/>
        public string dateModify {
            get {
                return this.dateModifyField;
            }
            set {
                this.dateModifyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getSessionKeyCompletedEventHandler(object sender, getSessionKeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSessionKeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSessionKeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void setLibraryCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void setContentCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void buildCacheCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591