CREATE TABLE [AdditionalDataSource] (
[Id] INTEGER  NOT NULL PRIMARY KEY,
[ExtId] BLOB  NOT NULL,
[Library_Id] INTEGER  NOT NULL REFERENCES [Library]([Id]),
[Path] VARCHAR(256) NOT NULL,
[Order] INTEGER NOT NULL,
[LastModified] DATETIME
)