//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesDepot.Services.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/SalesLibraries/content/quote?ws=1")]
        public string SalesDepot_Services_ContentManagmentService_ContentControllerService {
            get {
                return ((string)(this["SalesDepot_Services_ContentManagmentService_ContentControllerService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/SalesLibraries/admin/quote?ws=1")]
        public string SalesDepot_Services_IPadAdminService_AdminControllerService {
            get {
                return ((string)(this["SalesDepot_Services_IPadAdminService_AdminControllerService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/SalesLibraries/statistic/quote?ws=1")]
        public string SalesDepot_Services_StatisticService_StatisticControllerService {
            get {
                return ((string)(this["SalesDepot_Services_StatisticService_StatisticControllerService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/SalesLibraries/inactiveusers/quote?ws=1")]
        public string SalesDepot_Services_InactiveUsersService_InactiveUsersControllerService {
            get {
                return ((string)(this["SalesDepot_Services_InactiveUsersService_InactiveUsersControllerService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/SalesLibraries/qbuilder/quote?ws=1")]
        public string SalesDepot_Services_QBuilderService_QbuilderControllerService {
            get {
                return ((string)(this["SalesDepot_Services_QBuilderService_QbuilderControllerService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/SalesLibraries/utility/quote?ws=1")]
        public string SalesDepot_Services_UtilityService_UtilityControllerService {
            get {
                return ((string)(this["SalesDepot_Services_UtilityService_UtilityControllerService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/SalesLibraries/fileManagerData/quote?ws=1")]
        public string SalesDepot_Services_FileManagerDataService_FileManagerDataControllerService {
            get {
                return ((string)(this["SalesDepot_Services_FileManagerDataService_FileManagerDataControllerService"]));
            }
        }
    }
}
