CREATE TABLE [LibraryLink1] (
[Id] INTEGER NOT NULL PRIMARY KEY,
[ExtId] BLOB NOT NULL,
[Folder_Id] INTEGER REFERENCES [LibraryFolder]([Id]),
[FolderLink_Id] INTEGER REFERENCES [LibraryLink]([Id]),
[Name] VARCHAR(128),
[Type] INTEGER NOT NULL,
[Order] INTEGER NOT NULL,
[RelativePath] VARCHAR(256),
[IsDead] INTEGER,
[DataSourceId] BLOB,
[AddDate] DATETIME,
[LastModified] DATETIME,
[SettingsEncoded] TEXT,
[ExpirationEncoded] TEXT,
[SecurityEncoded] TEXT,
[TagsEncoded] TEXT,
[WidgetEncoded] TEXT,
[BannerEncoded] TEXT,
[ResetSettingsSchedulerEncoded] TEXT, 
[QuickLinkEncoded] TEXT, 
[ThumbnailEncoded] TEXT, 
[Discriminator] VARCHAR(128) NOT NULL 
);
INSERT INTO [LibraryLink1] 
SELECT 
	[Id],
	[ExtId],
	[Folder_Id],
	[FolderLink_Id],
	[Name],
	[Type],
	[Order],
	[RelativePath],
	[IsDead],
	[DataSourceId],
	[AddDate],
	[LastModified],
	[SettingsEncoded],
	[ExpirationEncoded],
	[SecurityEncoded],
	[TagsEncoded],
	[WidgetEncoded],
	[BannerEncoded],
	[ResetSettingsSchedulerEncoded], 
	[QuickLinkEncoded], 
	[ThumbnailEncoded], 
	[Discriminator]
FROM [LibraryLink];
DROP TABLE [LibraryLink];
CREATE TABLE [LibraryLink] (
[Id] INTEGER NOT NULL PRIMARY KEY,
[ExtId] BLOB NOT NULL,
[Folder_Id] INTEGER REFERENCES [LibraryFolder]([Id]),
[FolderLink_Id] INTEGER REFERENCES [LibraryLink]([Id]),
[Name] VARCHAR(128),
[Type] INTEGER NOT NULL,
[Order] INTEGER NOT NULL,
[RelativePath] VARCHAR(256),
[IsDead] INTEGER,
[DataSourceId] BLOB,
[AddDate] DATETIME,
[LastModified] DATETIME,
[SettingsEncoded] TEXT,
[ExpirationEncoded] TEXT,
[SecurityEncoded] TEXT,
[TagsEncoded] TEXT,
[WidgetEncoded] TEXT,
[BannerEncoded] TEXT,
[ResetSettingsSchedulerEncoded] TEXT, 
[QuickLinkEncoded] TEXT, 
[ThumbnailEncoded] TEXT, 
[Discriminator] VARCHAR(128) NOT NULL 
);
INSERT INTO [LibraryLink] 
SELECT 
	[Id],
	[ExtId],
	[Folder_Id],
	[FolderLink_Id],
	[Name],
	[Type],
	[Order],
	[RelativePath],
	[IsDead],
	[DataSourceId],
	[AddDate],
	[LastModified],
	[SettingsEncoded],
	[ExpirationEncoded],
	[SecurityEncoded],
	[TagsEncoded],
	[WidgetEncoded],
	[BannerEncoded],
	[ResetSettingsSchedulerEncoded], 
	[QuickLinkEncoded], 
	[ThumbnailEncoded], 
	[Discriminator]
FROM [LibraryLink1];
DROP TABLE [LibraryLink1];