//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SalesLibraries.ServiceConnector.LinkConfigProfileService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="LinkConfigProfileControllerBinding", Namespace="urn:LinkConfigProfileControllerwsdl")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(LibraryLinkReference))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(SecurityGroupReference))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(LibraryReference))]
    public partial class LinkConfigProfileControllerService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getLibrariesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSecurityGroupsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getProfilesOperationCompleted;
        
        private System.Threading.SendOrPostCallback saveProfileOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteProfileOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAffectedLinksOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMetaDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSessionKeyOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public LinkConfigProfileControllerService() {
            this.Url = global::SalesLibraries.ServiceConnector.Properties.Settings.Default.SalesLibraries_ServiceConnector_LinkConfigProfileService_LinkConfigProfileControllerService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getLibrariesCompletedEventHandler getLibrariesCompleted;
        
        /// <remarks/>
        public event getSecurityGroupsCompletedEventHandler getSecurityGroupsCompleted;
        
        /// <remarks/>
        public event getProfilesCompletedEventHandler getProfilesCompleted;
        
        /// <remarks/>
        public event saveProfileCompletedEventHandler saveProfileCompleted;
        
        /// <remarks/>
        public event deleteProfileCompletedEventHandler deleteProfileCompleted;
        
        /// <remarks/>
        public event getAffectedLinksCompletedEventHandler getAffectedLinksCompleted;
        
        /// <remarks/>
        public event getMetaDataCompletedEventHandler getMetaDataCompleted;
        
        /// <remarks/>
        public event getSessionKeyCompletedEventHandler getSessionKeyCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:LinkConfigProfileControllerwsdl#getLibraries", RequestNamespace="urn:LinkConfigProfileControllerwsdl", ResponseNamespace="urn:LinkConfigProfileControllerwsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public LibraryReference[] getLibraries(string sessionKey) {
            object[] results = this.Invoke("getLibraries", new object[] {
                        sessionKey});
            return ((LibraryReference[])(results[0]));
        }
        
        /// <remarks/>
        public void getLibrariesAsync(string sessionKey) {
            this.getLibrariesAsync(sessionKey, null);
        }
        
        /// <remarks/>
        public void getLibrariesAsync(string sessionKey, object userState) {
            if ((this.getLibrariesOperationCompleted == null)) {
                this.getLibrariesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetLibrariesOperationCompleted);
            }
            this.InvokeAsync("getLibraries", new object[] {
                        sessionKey}, this.getLibrariesOperationCompleted, userState);
        }
        
        private void OngetLibrariesOperationCompleted(object arg) {
            if ((this.getLibrariesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getLibrariesCompleted(this, new getLibrariesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:LinkConfigProfileControllerwsdl#getSecurityGroups", RequestNamespace="urn:LinkConfigProfileControllerwsdl", ResponseNamespace="urn:LinkConfigProfileControllerwsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public SecurityGroupReference[] getSecurityGroups(string sessionKey) {
            object[] results = this.Invoke("getSecurityGroups", new object[] {
                        sessionKey});
            return ((SecurityGroupReference[])(results[0]));
        }
        
        /// <remarks/>
        public void getSecurityGroupsAsync(string sessionKey) {
            this.getSecurityGroupsAsync(sessionKey, null);
        }
        
        /// <remarks/>
        public void getSecurityGroupsAsync(string sessionKey, object userState) {
            if ((this.getSecurityGroupsOperationCompleted == null)) {
                this.getSecurityGroupsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSecurityGroupsOperationCompleted);
            }
            this.InvokeAsync("getSecurityGroups", new object[] {
                        sessionKey}, this.getSecurityGroupsOperationCompleted, userState);
        }
        
        private void OngetSecurityGroupsOperationCompleted(object arg) {
            if ((this.getSecurityGroupsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSecurityGroupsCompleted(this, new getSecurityGroupsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:LinkConfigProfileControllerwsdl#getProfiles", RequestNamespace="urn:LinkConfigProfileControllerwsdl", ResponseNamespace="urn:LinkConfigProfileControllerwsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public LinkConfigProfileModel[] getProfiles(string sessionKey) {
            object[] results = this.Invoke("getProfiles", new object[] {
                        sessionKey});
            return ((LinkConfigProfileModel[])(results[0]));
        }
        
        /// <remarks/>
        public void getProfilesAsync(string sessionKey) {
            this.getProfilesAsync(sessionKey, null);
        }
        
        /// <remarks/>
        public void getProfilesAsync(string sessionKey, object userState) {
            if ((this.getProfilesOperationCompleted == null)) {
                this.getProfilesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetProfilesOperationCompleted);
            }
            this.InvokeAsync("getProfiles", new object[] {
                        sessionKey}, this.getProfilesOperationCompleted, userState);
        }
        
        private void OngetProfilesOperationCompleted(object arg) {
            if ((this.getProfilesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getProfilesCompleted(this, new getProfilesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:LinkConfigProfileControllerwsdl#saveProfile", RequestNamespace="urn:LinkConfigProfileControllerwsdl", ResponseNamespace="urn:LinkConfigProfileControllerwsdl")]
        public void saveProfile(string sessionKey, LinkConfigProfileModel profile) {
            this.Invoke("saveProfile", new object[] {
                        sessionKey,
                        profile});
        }
        
        /// <remarks/>
        public void saveProfileAsync(string sessionKey, LinkConfigProfileModel profile) {
            this.saveProfileAsync(sessionKey, profile, null);
        }
        
        /// <remarks/>
        public void saveProfileAsync(string sessionKey, LinkConfigProfileModel profile, object userState) {
            if ((this.saveProfileOperationCompleted == null)) {
                this.saveProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsaveProfileOperationCompleted);
            }
            this.InvokeAsync("saveProfile", new object[] {
                        sessionKey,
                        profile}, this.saveProfileOperationCompleted, userState);
        }
        
        private void OnsaveProfileOperationCompleted(object arg) {
            if ((this.saveProfileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.saveProfileCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:LinkConfigProfileControllerwsdl#deleteProfile", RequestNamespace="urn:LinkConfigProfileControllerwsdl", ResponseNamespace="urn:LinkConfigProfileControllerwsdl")]
        public void deleteProfile(string sessionKey, LinkConfigProfileModel profile) {
            this.Invoke("deleteProfile", new object[] {
                        sessionKey,
                        profile});
        }
        
        /// <remarks/>
        public void deleteProfileAsync(string sessionKey, LinkConfigProfileModel profile) {
            this.deleteProfileAsync(sessionKey, profile, null);
        }
        
        /// <remarks/>
        public void deleteProfileAsync(string sessionKey, LinkConfigProfileModel profile, object userState) {
            if ((this.deleteProfileOperationCompleted == null)) {
                this.deleteProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteProfileOperationCompleted);
            }
            this.InvokeAsync("deleteProfile", new object[] {
                        sessionKey,
                        profile}, this.deleteProfileOperationCompleted, userState);
        }
        
        private void OndeleteProfileOperationCompleted(object arg) {
            if ((this.deleteProfileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteProfileCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:LinkConfigProfileControllerwsdl#getAffectedLinks", RequestNamespace="urn:LinkConfigProfileControllerwsdl", ResponseNamespace="urn:LinkConfigProfileControllerwsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public LibraryLinkReference[] getAffectedLinks(string sessionKey, LinkConfigProfileModel profile) {
            object[] results = this.Invoke("getAffectedLinks", new object[] {
                        sessionKey,
                        profile});
            return ((LibraryLinkReference[])(results[0]));
        }
        
        /// <remarks/>
        public void getAffectedLinksAsync(string sessionKey, LinkConfigProfileModel profile) {
            this.getAffectedLinksAsync(sessionKey, profile, null);
        }
        
        /// <remarks/>
        public void getAffectedLinksAsync(string sessionKey, LinkConfigProfileModel profile, object userState) {
            if ((this.getAffectedLinksOperationCompleted == null)) {
                this.getAffectedLinksOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAffectedLinksOperationCompleted);
            }
            this.InvokeAsync("getAffectedLinks", new object[] {
                        sessionKey,
                        profile}, this.getAffectedLinksOperationCompleted, userState);
        }
        
        private void OngetAffectedLinksOperationCompleted(object arg) {
            if ((this.getAffectedLinksCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAffectedLinksCompleted(this, new getAffectedLinksCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:LinkConfigProfileControllerwsdl#getMetaData", RequestNamespace="urn:LinkConfigProfileControllerwsdl", ResponseNamespace="urn:LinkConfigProfileControllerwsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string getMetaData(string sessionKey, string dataTag, string propertyName) {
            object[] results = this.Invoke("getMetaData", new object[] {
                        sessionKey,
                        dataTag,
                        propertyName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getMetaDataAsync(string sessionKey, string dataTag, string propertyName) {
            this.getMetaDataAsync(sessionKey, dataTag, propertyName, null);
        }
        
        /// <remarks/>
        public void getMetaDataAsync(string sessionKey, string dataTag, string propertyName, object userState) {
            if ((this.getMetaDataOperationCompleted == null)) {
                this.getMetaDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMetaDataOperationCompleted);
            }
            this.InvokeAsync("getMetaData", new object[] {
                        sessionKey,
                        dataTag,
                        propertyName}, this.getMetaDataOperationCompleted, userState);
        }
        
        private void OngetMetaDataOperationCompleted(object arg) {
            if ((this.getMetaDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMetaDataCompleted(this, new getMetaDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:LinkConfigProfileControllerwsdl#getSessionKey", RequestNamespace="urn:LinkConfigProfileControllerwsdl", ResponseNamespace="urn:LinkConfigProfileControllerwsdl")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string getSessionKey(string login, string password) {
            object[] results = this.Invoke("getSessionKey", new object[] {
                        login,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getSessionKeyAsync(string login, string password) {
            this.getSessionKeyAsync(login, password, null);
        }
        
        /// <remarks/>
        public void getSessionKeyAsync(string login, string password, object userState) {
            if ((this.getSessionKeyOperationCompleted == null)) {
                this.getSessionKeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSessionKeyOperationCompleted);
            }
            this.InvokeAsync("getSessionKey", new object[] {
                        login,
                        password}, this.getSessionKeyOperationCompleted, userState);
        }
        
        private void OngetSessionKeyOperationCompleted(object arg) {
            if ((this.getSessionKeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSessionKeyCompleted(this, new getSessionKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:LinkConfigProfileControllerwsdl")]
    public partial class LibraryReference {
        
        private string idField;
        
        private string nameField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:LinkConfigProfileControllerwsdl")]
    public partial class LibraryLinkReference {
        
        private string idField;
        
        private string nameField;
        
        private string fileNameField;
        
        private string filePathField;
        
        private string libraryNameField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        public string filePath {
            get {
                return this.filePathField;
            }
            set {
                this.filePathField = value;
            }
        }
        
        /// <remarks/>
        public string libraryName {
            get {
                return this.libraryNameField;
            }
            set {
                this.libraryNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:LinkConfigProfileControllerwsdl")]
    public partial class LinkProfileSettings {
        
        private bool disablePreviewField;
        
        private bool disableDownloadField;
        
        private bool disableQuickSiteField;
        
        private bool disableFavoritesField;
        
        private bool disableSaveField;
        
        private bool disableEmailField;
        
        private bool disablePdfField;
        
        private string[] libraryLinkTagsField;
        
        private LibraryReference[] libraryReferencesField;
        
        private SecurityGroupReference[] securityGroupReferencesField;
        
        private LibraryLinkReference[] ignoredLinkReferencesField;
        
        /// <remarks/>
        public bool disablePreview {
            get {
                return this.disablePreviewField;
            }
            set {
                this.disablePreviewField = value;
            }
        }
        
        /// <remarks/>
        public bool disableDownload {
            get {
                return this.disableDownloadField;
            }
            set {
                this.disableDownloadField = value;
            }
        }
        
        /// <remarks/>
        public bool disableQuickSite {
            get {
                return this.disableQuickSiteField;
            }
            set {
                this.disableQuickSiteField = value;
            }
        }
        
        /// <remarks/>
        public bool disableFavorites {
            get {
                return this.disableFavoritesField;
            }
            set {
                this.disableFavoritesField = value;
            }
        }
        
        /// <remarks/>
        public bool disableSave {
            get {
                return this.disableSaveField;
            }
            set {
                this.disableSaveField = value;
            }
        }
        
        /// <remarks/>
        public bool disableEmail {
            get {
                return this.disableEmailField;
            }
            set {
                this.disableEmailField = value;
            }
        }
        
        /// <remarks/>
        public bool disablePdf {
            get {
                return this.disablePdfField;
            }
            set {
                this.disablePdfField = value;
            }
        }
        
        /// <remarks/>
        public string[] libraryLinkTags {
            get {
                return this.libraryLinkTagsField;
            }
            set {
                this.libraryLinkTagsField = value;
            }
        }
        
        /// <remarks/>
        public LibraryReference[] libraryReferences {
            get {
                return this.libraryReferencesField;
            }
            set {
                this.libraryReferencesField = value;
            }
        }
        
        /// <remarks/>
        public SecurityGroupReference[] securityGroupReferences {
            get {
                return this.securityGroupReferencesField;
            }
            set {
                this.securityGroupReferencesField = value;
            }
        }
        
        /// <remarks/>
        public LibraryLinkReference[] ignoredLinkReferences {
            get {
                return this.ignoredLinkReferencesField;
            }
            set {
                this.ignoredLinkReferencesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:LinkConfigProfileControllerwsdl")]
    public partial class SecurityGroupReference {
        
        private string idField;
        
        private string nameField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:LinkConfigProfileControllerwsdl")]
    public partial class LinkConfigProfileModel {
        
        private string idField;
        
        private string nameField;
        
        private int orderField;
        
        private LinkProfileSettings configField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
        
        /// <remarks/>
        public LinkProfileSettings config {
            get {
                return this.configField;
            }
            set {
                this.configField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void getLibrariesCompletedEventHandler(object sender, getLibrariesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getLibrariesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getLibrariesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LibraryReference[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LibraryReference[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void getSecurityGroupsCompletedEventHandler(object sender, getSecurityGroupsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSecurityGroupsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSecurityGroupsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SecurityGroupReference[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SecurityGroupReference[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void getProfilesCompletedEventHandler(object sender, getProfilesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getProfilesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getProfilesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LinkConfigProfileModel[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LinkConfigProfileModel[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void saveProfileCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void deleteProfileCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void getAffectedLinksCompletedEventHandler(object sender, getAffectedLinksCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAffectedLinksCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAffectedLinksCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LibraryLinkReference[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LibraryLinkReference[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void getMetaDataCompletedEventHandler(object sender, getMetaDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMetaDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMetaDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void getSessionKeyCompletedEventHandler(object sender, getSessionKeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSessionKeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSessionKeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591